export const characters = [
  {
    id: 'gojo',
    name: 'Satoru Gojo',
    kana: '五条 悟',
    grade: 'Special',
    affiliation: 'Tokyo Jujutsu High',
    technique: 'Limitless',
    domain: 'Unlimited Void',
    color: '#4cc9f0',
    quote: 'Throughout heaven and earth, I alone am the honored one.',
    bio: 'The strongest sorcerer alive. Inherits both the Limitless technique and the Six Eyes, a combination that had not appeared in centuries.',
    stats: { power: 10, technique: 10, speed: 9, wits: 9 },
  },
  {
    id: 'yuji',
    name: 'Yuji Itadori',
    kana: '虎杖 悠仁',
    grade: 'Grade 1',
    affiliation: 'Tokyo Jujutsu High',
    technique: 'Divergent Fist',
    domain: '—',
    color: '#f72585',
    quote: "I don't know how I'll feel when I'm dead, but I don't want to regret the way I lived.",
    bio: "Sukuna's vessel. A first-year with monstrous physical ability who swallowed a cursed finger to save his friends.",
    stats: { power: 8, technique: 5, speed: 8, wits: 6 },
  },
  {
    id: 'megumi',
    name: 'Megumi Fushiguro',
    kana: '伏黒 恵',
    grade: 'Grade 2',
    affiliation: 'Tokyo Jujutsu High',
    technique: 'Ten Shadows',
    domain: 'Chimera Shadow Garden',
    color: '#3a0ca3',
    quote: 'I am not a hero. I am a jujutsu sorcerer.',
    bio: 'Heir to the Zenin ten shadows technique. Summons shikigami from his shadow and fights with cold, calculated efficiency.',
    stats: { power: 7, technique: 9, speed: 7, wits: 9 },
  },
  {
    id: 'nobara',
    name: 'Nobara Kugisaki',
    kana: '釘崎 野薔薇',
    grade: 'Grade 3',
    affiliation: 'Tokyo Jujutsu High',
    technique: 'Straw Doll',
    domain: '—',
    color: '#ff9e00',
    quote: 'I love myself when I look pretty and strong.',
    bio: 'A first-year from the countryside who fights with a hammer and nails, channeling cursed energy through resonance.',
    stats: { power: 7, technique: 8, speed: 6, wits: 7 },
  },
  {
    id: 'nanami',
    name: 'Kento Nanami',
    kana: '七海 建人',
    grade: 'Grade 1',
    affiliation: 'Tokyo Jujutsu High',
    technique: 'Ratio Technique',
    domain: '—',
    color: '#c9a227',
    quote: 'Working is evil. There is no such thing as noble labor.',
    bio: 'A former salaryman who returned to sorcery. Splits any target into a 7:3 ratio and strikes the weak point.',
    stats: { power: 8, technique: 8, speed: 7, wits: 9 },
  },
  {
    id: 'sukuna',
    name: 'Ryomen Sukuna',
    kana: '両面宿儺',
    grade: 'Special',
    affiliation: 'Curses',
    technique: 'Cleave & Dismantle',
    domain: 'Malevolent Shrine',
    color: '#d00000',
    quote: 'Stand proud. You are strong.',
    bio: 'The King of Curses. A four-armed sorcerer from the golden age whose twenty fingers were sealed rather than destroyed.',
    stats: { power: 10, technique: 10, speed: 10, wits: 9 },
  },
  {
    id: 'mahito',
    name: 'Mahito',
    kana: '真人',
    grade: 'Special',
    affiliation: 'Curses',
    technique: 'Idle Transfiguration',
    domain: 'Self-Embodiment of Perfection',
    color: '#7209b7',
    quote: 'The shape of the soul is the shape of the body.',
    bio: 'A cursed spirit born from human hatred of one another. Reshapes souls on contact, killing or transforming instantly.',
    stats: { power: 8, technique: 10, speed: 8, wits: 8 },
  },
  {
    id: 'maki',
    name: 'Maki Zenin',
    kana: '禪院 真希',
    grade: 'Grade 4',
    affiliation: 'Tokyo Jujutsu High',
    technique: 'Heavenly Restriction',
    domain: '—',
    color: '#2a9d8f',
    quote: "I'll show them what a Zenin without cursed energy can do.",
    bio: 'Born with no cursed energy and superhuman physicality. Wields cursed tools to overwhelm sorcerers who underestimate her.',
    stats: { power: 9, technique: 4, speed: 9, wits: 7 },
  },
  {
    id: 'toge',
    name: 'Toge Inumaki',
    kana: '狗巻 棘',
    grade: 'Grade 2',
    affiliation: 'Tokyo Jujutsu High',
    technique: 'Cursed Speech',
    domain: '—',
    color: '#90be6d',
    quote: 'Salmon.',
    bio: 'Speaks only in rice ball ingredients to avoid cursing those around him. His words compel anyone who hears them.',
    stats: { power: 6, technique: 9, speed: 6, wits: 7 },
  },
  {
    id: 'panda',
    name: 'Panda',
    kana: 'パンダ',
    grade: 'Grade 2',
    affiliation: 'Tokyo Jujutsu High',
    technique: 'Cursed Corpse Cores',
    domain: '—',
    color: '#8d99ae',
    quote: "I'm not a panda. I'm a panda-type cursed corpse.",
    bio: 'A mutated cursed corpse created by Principal Yaga, with three cores that let him switch combat forms mid-fight.',
    stats: { power: 8, technique: 6, speed: 7, wits: 7 },
  },
  {
    id: 'geto',
    name: 'Suguru Geto',
    kana: '夏油 傑',
    grade: 'Special',
    affiliation: 'Curses',
    technique: 'Cursed Spirit Manipulation',
    domain: '—',
    color: '#480ca8',
    quote: 'Are monkeys worth protecting?',
    bio: "Gojo's former best friend turned curse user. Absorbs and commands defeated cursed spirits as an army.",
    stats: { power: 9, technique: 10, speed: 8, wits: 9 },
  },
  {
    id: 'todo',
    name: 'Aoi Todo',
    kana: '東堂 葵',
    grade: 'Grade 1',
    affiliation: 'Kyoto Jujutsu High',
    technique: 'Boogie Woogie',
    domain: '—',
    color: '#e63946',
    quote: 'What kind of woman is your type?',
    bio: 'A Kyoto third-year who swaps the positions of anything with cursed energy by clapping. Yuji\'s self-declared best friend.',
    stats: { power: 9, technique: 8, speed: 8, wits: 8 },
  },
  {
    id: 'yuta',
    name: 'Yuta Okkotsu',
    kana: '乙骨 憂太',
    grade: 'Special',
    affiliation: 'Tokyo Jujutsu High',
    technique: 'Copy',
    domain: 'Authentic Mutual Love',
    color: '#4361ee',
    quote: "I don't understand loving yourself, but I'd die for someone else.",
    bio: 'A special grade who fights alongside the cursed spirit of his childhood friend Rika, and can borrow the techniques of sorcerers he has seen use them.',
    stats: { power: 9, technique: 9, speed: 9, wits: 7 },
  },
  {
    id: 'higuruma',
    name: 'Hiromi Higuruma',
    kana: '日車 寛見',
    grade: 'Grade 1',
    affiliation: 'Tokyo Jujutsu High',
    technique: 'Deadly Sentencing',
    domain: 'Deadly Sentencing',
    color: '#6d597a',
    quote: 'The law is not justice. It is the shape justice was forced into.',
    bio: 'A burned-out defense attorney who awakened a technique that puts his opponent on trial — and hands down a sentence the domain enforces.',
    stats: { power: 7, technique: 10, speed: 8, wits: 10 },
  },
  {
    id: 'kamo',
    name: 'Noritoshi Kamo',
    kana: '加茂 憲紀',
    grade: 'Grade 2',
    affiliation: 'Kyoto Jujutsu High',
    technique: 'Blood Manipulation',
    domain: '—',
    color: '#9d0208',
    quote: 'I carry the name Kamo. That is not a thing you put down.',
    bio: 'Heir to the Kamo clan and captain of the Kyoto second-years. Fires his own blood as arrows and supercharges his body by manipulating it inward.',
    stats: { power: 7, technique: 8, speed: 7, wits: 8 },
  },
  {
    id: 'miwa',
    name: 'Kasumi Miwa',
    kana: '三輪 霞',
    grade: 'Grade 3',
    affiliation: 'Kyoto Jujutsu High',
    technique: 'New Shadow Style',
    domain: '—',
    color: '#00b4d8',
    quote: 'I only became a sorcerer for the money, honestly.',
    bio: 'A Kyoto second-year with no innate technique who compensates with the New Shadow Style and Simple Domain — pure swordsmanship, endlessly drilled.',
    stats: { power: 5, technique: 6, speed: 7, wits: 6 },
  },
  {
    id: 'mai',
    name: 'Mai Zenin',
    kana: '禪院 真依',
    grade: 'Grade 3',
    affiliation: 'Kyoto Jujutsu High',
    technique: 'Construction',
    domain: '—',
    color: '#b5838d',
    quote: 'Stay away from me. Both of us know how that ends.',
    bio: "Maki's twin sister, kept by the Zenin clan for a technique that creates matter from cursed energy — at a steep cost to her every time she uses it.",
    stats: { power: 5, technique: 7, speed: 6, wits: 7 },
  },
  {
    id: 'mechamaru',
    name: 'Kokichi Muta',
    kana: '与 幸吉',
    grade: 'Grade 2',
    affiliation: 'Kyoto Jujutsu High',
    technique: 'Puppet Manipulation',
    domain: '—',
    color: '#9c6644',
    quote: 'This body is the puppet. I am somewhere much less convenient.',
    bio: 'Fights entirely through the mechanized puppet Mechamaru, piloted from a distance because a heavenly restriction leaves his real body unable to move.',
    stats: { power: 7, technique: 9, speed: 5, wits: 9 },
  },
  {
    id: 'toji',
    name: 'Toji Fushiguro',
    kana: '伏黒 甚爾',
    grade: 'Unranked',
    affiliation: 'Curse Users',
    technique: 'None — Heavenly Restriction',
    domain: '—',
    color: '#4a4e69',
    quote: 'You need cursed energy to see me coming. I don\'t have any.',
    bio: 'Born into the Zenin clan without a drop of cursed energy and with a body that broke the ceiling instead. Sells cursed tools and assassinations for whatever he can bet on.',
    stats: { power: 10, technique: 1, speed: 10, wits: 8 },
  },
  {
    id: 'choso',
    name: 'Choso',
    kana: '脹相',
    grade: 'Special',
    affiliation: 'Curses',
    technique: 'Blood Manipulation',
    domain: '—',
    color: '#6a040f',
    quote: 'I am the eldest of nine. That is reason enough to fight.',
    bio: 'A death painting womb — half human, half cursed spirit — who manipulates his own blood at a range and precision no Kamo sorcerer has matched.',
    stats: { power: 8, technique: 9, speed: 8, wits: 8 },
  },
  {
    id: 'uraume',
    name: 'Uraume',
    kana: '裏梅',
    grade: 'Special',
    affiliation: 'Curse Users',
    technique: 'Ice Formation',
    domain: '—',
    color: '#89c2d9',
    quote: 'Sukuna-sama will be pleased.',
    bio: "A curse user from the golden age of jujutsu, loyal to Sukuna and still keeping his kitchen. Freezes the air itself with Ice Formation.",
    stats: { power: 8, technique: 9, speed: 7, wits: 9 },
  },
  {
    id: 'dagon',
    name: 'Dagon',
    kana: 'ダゴン',
    grade: 'Special',
    affiliation: 'Curses',
    technique: 'Shikigami Manipulation',
    domain: 'Horizon of the Captive Whale',
    color: '#0096c7',
    quote: '—',
    bio: 'A disaster curse born of humanity\'s fear of the sea. Fills its domain with deep-water shikigami that never miss what is already drowning.',
    stats: { power: 8, technique: 8, speed: 6, wits: 6 },
  },
]

export const grades = ['All', 'Special', 'Grade 1', 'Grade 2', 'Grade 3', 'Grade 4', 'Unranked']

export const affiliations = [
  'All',
  'Tokyo Jujutsu High',
  'Kyoto Jujutsu High',
  'Curses',
  'Curse Users',
]
